name: Build Android APK

on:
  workflow_dispatch: # This allows you to manually trigger the build

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu' # A highly compatible Java distribution for Android
          java-version: '17'   # Change to '11' if the project is a few years old

      - name: Make Gradle Wrapper executable
        run: chmod +x ./gradlew
        working-directory: ./android

      - name: Build APK
        run: ./gradlew assembleDebug
        working-directory: ./android
        
      - name: Upload APK as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          # Notice we also updated the path here to start inside the android folder
          path: android/app/build/outputs/apk/debug/**/*.apk
